language: racket

env:
 - RACKET_VERSION=HEAD

before_install:
- git clone https://github.com/greghendershott/travis-racket.git
- cat travis-racket/install-racket.sh | bash # pipe to bash not sh!

install:

before_script:

script:
 - cd ./benchmarks
 - /usr/racket/bin/raco test "./run unit-tests.rkt"

after_script: